image: "rust:latest"

lint:fmt:
  before_script:
    - rustup component add rustfmt
  script:
    - cargo fmt -- --check
  allow_failure: true

test:cargo:
  before_script:
    - apt update -y
    - apt install -y autoconf-archive
  script:
    - ./autogen.sh
    - ./configure
    - make check-local
